flags: {}
packages:
- '.'
- location:
    git: https://github.com/SFML-haskell/SFML.git
    commit: 379ec6c107d925445f52c2c7f4fdd261a0c946e5
extra-deps: []
resolver: lts-3.12
ghc-options:
  SFML: -fsimpl-tick-factor=10000
